### PR TITLE
Display the list of config files in the sandbox #281

### PR DESCRIPTION
**Pull request by pmi**

### CODE REVIEW

**Review by rymsha — CHANGES_REQUESTED** [review]
There is a system property `xp.config.paths`. (Multiple paths are allowed)
Its default value is `${xp.home}/config`
So, code won't work if system property is set to something else

**Comment by pmi** [comment]
As far as I can see, there are few ways to fix it:
- corresponding method should be added `com.enonic.xp.home.HomeDir` from `core-api` module 
- `com.enonic.xp.server.internal.config.ConfigPaths` should be added to `core-api`

I don't like the idea of reading system property manually since multiple paths are allowed and format is unknown (besides ConfigPaths does it already)

**Review by rymsha — APPROVED** [review]
I changed my mind. I don't want it to be overcomplicated. Welcome is part of SDK only where config path is more or less static.

**Review by alansemenov — CHANGES_REQUESTED** [review]
1. We need to sort the list alphabetically
2. We need to whitelist extensions (`.cfg`, `.properties`, `.xml`). In the screenshot there is `.DS_Store` file in the list which is a system file that we don't need to show.
3. We need "Copy to clipboard" icon on the heading line (path to the config folder) as well, to copy the path to buffer and do "`cd path-to-folder`", for instance. This icon should be always visible (not only on hover).
4. All the "copy to clipboard" icons should have a **localised** tooltip (`title` attribute): "Copy to clipboard".

image

**Review by alansemenov — APPROVED** [review]

**Pull request merged**
